version: '2'

services:
  web:
    build: .
    command: bash -c "python holmes/Holmes/manage.py makemigrations && python holmes/Holmes/manage.py migrate && python holmes/Holmes/manage.py runserver 0.0.0.0:8000"
    container_name: holmes
    volumes:
      - ./bam_files/:/bam_files
      - ./annotations/:/annotations/
      - ./ref_genome/:/ref_genome/
    ports:
      - "8000:8000"
