version: '2'

services:
  web:
    build: .
    command: bash -c "cd /holmes/Holmes/ && git pull && python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    container_name: holmes
    volumes:
      - ./bam_files/:/bam_files
      - ./annotations/:/annotations/
      - ./ref_genome/:/ref_genome/
    ports:
      - "8000:8000"
